server:
  port: 8080

spring:
  boot:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/gunmarketx
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    separator: ;;
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.lob.non_contextual_creation: true
        format_sql: true

logging:
  file:
    name: aggregator-app.log
